### ISSUE TITLE
removeOutOfBoundsReads.pI not working

### ISSUE THREAD

**Issue by rb56** [IGBIllinois/HOMER#1]
Hello,

I'm trying to use Homer on my local computer to remove out of bound reads from .bam files. But everytime I try running the removeOutOfBoundsReads.pI <path to Bam Folder> hg19 command, I get an error that homer cannot find the chromosome size file. The genome folder in homer/bin has the chromosome.size file so I'm not sure what the error really means.
<img width="1161" alt="Screen Shot 2020-08-27 at 8 43 10 PM 1" src="https://user-images.githubusercontent.com/62675463/91668561-8c408f00-eadb-11ea-986d-8bf65860c32d.png">
Here is what the error looks like

Thanks in advance!

**Comment by dslater82** [comment]
Hi, you should contact the actual HOMER people at http://homer.ucsd.edu/homer/.  This repository is a copy of their code which allows it to work on multiuser systems due to our own HPC cluster needs.  We haven't touched this in a while and are a few versions behind.

**Comment by rb56** [comment]
Thanks!!
