### ISSUE TITLE
HOMER Could not open peak/position file

### ISSUE THREAD

**Issue by danielcgingerich** [IGBIllinois/HOMER#2]
am trying to do motif analysis on a set of ATAC peaks with findMotifsGenome.pl using HOMER installed on a computer cluster. I submit a simple slurm job:

```
#!/bin/bash
#SBATCH -J HOMER.test
#SBATCH -o %A_%a.out.txt
#SBATCH -e %A_%a.err.txt
#SBATCH --mem=24G
#SBATCH -n 8
#SBATCH --mail-type=END
#SBATCH --mail-user=xxyyxx@institution.edu

findMotifsGenome.pl homer.peaks.test.txt GRCh38.p13.genome.fa ./homer.test/ -size 200 -mask
```
and receive the following .err.txt file:

```
    Position file = homer.peaks.test.txt
    Genome = GRCh38.p13.genome.fa
    Output Directory = ./homer.test/
    Fragment size set to 200
    Will use repeat masked sequences
    Using Custom Genome
!!! Could not open peak/position file homer.peaks.test.txt !!!
```
I formatted the peak.txt file tab delimited with all the columns specified on the website.

**Comment by dslater82** [comment]
Hi,

This is an unofficial port of HOMER so it can work from a shared installation on a cluster.  I think the question you have would be more appropriate to ask the actual developers at http://homer.ucsd.edu/homer/.
