### ISSUE TITLE
Computation of q-values (Benjamini)

### ISSUE THREAD

**Issue by bijuissacch224610** [IGBIllinois/HOMER#4]
Hi Team

I ran findMotifs.pl on a bunch of fasta sequences.
In the output folder, the known motif enrichment results also provides q values (Benjamini). Turns out that the qvalues are smaller than nominal p-values. Any idea why qvalues are smaller that pvalues?

BEst
-Biju
<img width="1057" alt="Screen Shot 2023-02-22 at 10 33 58 AM" src="https://user-images.githubusercontent.com/83024487/220747441-0e02ddf0-5fb5-4640-a3ba-e3cf40221c45.png">

**Comment by dslater82** [comment]
Hi this repo is a fork of homer that allows users to have their own databases in their home folders.  For these questions, you should contact the homer people directly at http://homer.ucsd.edu/.
