### ISSUE TITLE
to find motifs from genomic coordinates from gene list

### ISSUE THREAD

**Issue by klai001** [IGBIllinois/HOMER#5]
Hello,
Im trying to find transcriptional motifs within my core promoter regions of the genes in my list (i only have the gene list containing gene symbols, no FASTA files/ associated info).
Out of the commands in HOMER, i suppose findMotifsGenome.pl would be the closest.
Nevertheless from the BED output on UCSC genome browser, understandably so since its not a CHIPseq expt, there's no `unique PEAK output` as required by HOMER's findMotifsGenome.pl 
Am i thinking of the right command and workflow for this purpose?
Any suggestions appreciated

**Comment by dslater82** [comment]
Hi this repo is a fork of homer that allows users to have their own databases in their home folders. For these questions, you should contact the homer people directly at http://homer.ucsd.edu/.
